### PR TITLE
Adding support for free dynamic dns freemyip.com

### PR DESCRIPTION
**Pull request by Cadence-GitHub**
I tested to locally and it seems to be working fine.

### CODE REVIEW

**Comment by wimpunk** [comment]
Your patch looks great, thanks for pushing it.
Just a little question: do I see it correctly there is no login and the IP isn't fetched from anywhere?

**Comment by Cadence-GitHub** [comment]
@wimpunk Thanks for your comment.
Yes, you are correct. There is no login at freemyip.com, and the service detects client's IP address automatically, so there is no need to fetch IP.

I did some testing with updating from different IPs, and it worked correctly. I also tried some negative-case tests (wrong token, no token at all, etc) and the results and errors were as expected.

**Comment by Cadence-GitHub** [comment]
Hi @wimpunk 
Is there anything else I should be doing regarding this PR? I'm quite new to github, so am not very familiar with the whole PR procedure. If you still require anything from me, please let me know :)

**Comment by wimpunk** [comment]
Sorry, didn't had time to review and test it.

**Comment by wimpunk** [comment]
Found some time to review your suggestion.  Merged. :-)

**Comment by Cadence-GitHub** [comment]
That's great news, thanks @wimpunk. So exciting to see my code added to ddclient!

**Comment by glensc** [comment]
seems to be ddclient itself is unable to operate if it can't detect ip by itself. i had to configure `use=web` for ddclient even to attempt to submit registration

**Comment by glensc** [comment]
btw, their api supports passing ip as well:
- http://freemyip.com/help?domain=example.freemyip.com&token=exampletoken

> ### Can I point my domain to an arbitrary IP address?
> Yes. You can use an optional "&myip" parameter to do that. For example, to set your domain to point to IP 1.2.3.4 you need to use the following URL:
> ```
> https://freemyip.com/update?token=exampletoken&domain=example.freemyip.com&myip=1.2.3.4
> ```

**Pull request merged**
