### PR TITLE
Email protocol

### PR DESCRIPTION
**Pull request by iboisvert**
For people with internet-facing services that don't need or want a dynamic dns account.

### CODE REVIEW

**Comment by wimpunk** [comment]
I think I understand why you want this kind of feature.  Unfortunately your addition uses to much extra dependencies.  Since we are trying to add as less dependencies as possible, I believe it would be better to add an 'none' provider and configure a mail-option. That would add less to the current code.

**Comment by dkerr64** [comment]
Maybe a better way to do this would be to provide for a way to execute a command.  Right now ddclient lets you execute a command to obtain the IP address.   How about adding a feature to execute a command when an update is performed... passing in the obtained IP address (and maybe other flags like whether IPv6, what service was updated, etc.) as parameters.  In this case that command could be sendmail (wrapped in some shell script).  And it would add tremendous flexibility for other features as well.   As command execution is already supported this could be done with no additional dependencies.

**Comment by iboisvert** [comment]
Hi, thanks for sharing your thoughts. I agree, an email option would be
better than the provider, then it could be used conjunction with any of the
other providers as well. One other thing that I thought of, though, is that
there needs to be an additional option to specify a certificate to sign the
generated email, because these emails would be very easy to spoof.

Best regards,
Ian

**Comment by wimpunk** [comment]
@dkerr64 The option of running a script does already exist.  See the `postscript` option for more info.

**Pull request closed without merging**
