### PR TITLE
Support for woima.fi

### PR DESCRIPTION
**Pull request by jabaz**
Hi,
I just added support for woima.fi dyndns service.
woima.fi is finnish service provider, that provides dyndns service.
I also added fix and install instructions for ubuntu.

### CODE REVIEW

**Comment by wimpunk** [comment]
Your request looks promissing but I have a few questions:

1. I see you want woima.fi be supported but it looks pretty familiar to
dyndns.  I even saw you copied a little to much from dyndns.  It would be
better if you clean it a little
2. I saw you also made some changes to parts which does not have anything
to do with woima.  Please use a different pull request for that.
3. Please also add an example on how to configure the service
4. Is there any English URL to the API?

Sorry I make it that hard.

**Comment by jabaz** [comment]
How can i use different pull request?

**Comment by wimpunk** [comment]
I would use different branches for every different fix.  You can
branch your master tree from where you cloned mine and cherry pick the
commits you need.
This evening (EST) if I find some sparetime, I'll try to cherrypick
your ubuntu fix so all other fixes will be woima related.  Btw, do
they have an English version of their site?

**Comment by jabaz** [comment]
I joined those commits, for same things.
One commit for woima.fi and one commit for ubuntu.
I don't think they have english site!

**Comment by jabaz** [comment]
Now i created new branch named master-ubuntu, but i don't know how to cherry pick.

**Comment by jabaz** [comment]
I just managed to do cherry pick!
Now i have two pull requests.
I will clean that woima.fi when i got time!

**Comment by wimpunk** [comment]
You didn't had to clean this one. Since I could pick up the ubuntu patch, I could also apply this one. I really love git. :-)
And thank you very much for the patch.  I hope there will be some Finns will enjoy it.

**Comment by jabaz** [comment]
Thank you too. :)

**Pull request merged**
