### PR TITLE
Add support for Google Domains.

### PR DESCRIPTION
**Pull request by nelsonjr**
This change adds support to "googledomains" provider to handle Dynamic DNS entries hosted in Google Domains.

### CODE REVIEW

**Comment by wimpunk** [comment]
Can you remove the changes you did in the geturl part? They are not related to the google domains changes. Although you may create an extra pull request to clean up the code. :-)

**Comment by nelsonjr** [comment]
Sure. I will be happy to help with the cleanup as well.

**Comment by nelsonjr** [comment]
Done.

**Comment by nelsonjr** [comment]
Done. Please take another look. Thanks.


Best regards,
-- Nelson

**Pull request merged**
