### PR TITLE
Update CloudFlare from API v1 to API v4

### PR DESCRIPTION
**Pull request by Harry-Xue**
CloudFlare announced the sunset of its API v1 currently used by ddclient.

> We’re reaching out because we noticed you’re using CloudFlare’s API v1. Starting November 9th, 2016 at noon Pacific Time (20:00 UTC), CloudFlare will no longer be supporting API v1. CloudFlare uses API v4 to power our customer dashboard, so unlike API v1, it has support for every single feature on CloudFlare. We've written extensive documentation to help you migrate from v1 to v4 available here: [API v1 to v4 Migration Documentation](https://www.cloudflare.com/migrating-to-v4/).

These changes use CloudFlare API v4:

- List Zones: https://api.cloudflare.com/#zone-list-zones
- List DNS Records: https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records
- Update DNS Records: https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

Tested only with ipv4. Did not code for ipv6.

### CODE REVIEW

**Comment by ImpulseTheFox** [comment]
I've got an email today from CloudFlare warning me about use of the v1 API. ddclient is definitely the only application I use with the cloudflare API. CloudFlare says I've been using the v1 API in the last 30 days and it will be shutdown on June 4. How is this?

**Comment by noblueskydropfiles** [comment]
Got the same email. I suspect version 3.8.3-1.1 from Debian Stretch sources is much older than this one. It also seems the sourceforge version is outdated as well. I'm lost with version numbers there...
I added `libdata-validate-ip-perl`, replaced my binary with current one from this repo and removed troublesome conf line `server=www.cloudflare.com` in `ddclient.conf` (move `ddclient.conf` in `/etc/ddclient/`).
So far seems to work, but I would love if this got into official distro packages instead of making dirty changes.

**Comment by ImpulseTheFox** [comment]
Nice to see you've figured out a solution. Meanwhile I've created my own DNS entry updater though: https://gist.github.com/ImpulseTheFox/20ebdae07049d3f42467fb21ae445f05

**Comment by JohnVillalovos** [comment]
The reason it isn't in 3.8.3 is because 3.8.3 was released in 2015. There don't appear to be any newer releases :(

    commit 1d919b15a394b3b40fd1bb24ceb665d89d54b108 (HEAD, tag: refs/tags/v3.8.3)
    Author: Wim Vinckier <wimpunk@gmail.com>
    Date:   Thu May 28 22:05:05 2015 +0200

        Preparing for v3.8.3

Git tag only shows two tags:

    $ git tag
    v3.8.2
    v3.8.3

**Comment by wimpunk** [comment]
There's also a question about this on sf.net, see https://sourceforge.net/p/ddclient/discussion/399428/thread/dd949fe7/
I'll try to apply this patch asap.
And @JohnVillalovos, you're right, I should release a new version.  It's been a while since the last release.

**Comment by Denton-L** [comment]
+1 for a new release, please. Arch Linux doesn't want to release a new package until an official release is created: https://bugs.archlinux.org/task/58658?project=5&string=ddclient

**Comment by TeoTN** [comment]
My server's just stopped working because ddclient wasn't updated :/
Could anyone point me to an alternative app that works with Cloudflare APIv4?

**Comment by coultonluke** [comment]
My pi also stopped working.  Managed to @bosbefok's script working just fine.  Thanks for that.

**Comment by risturiz** [comment]
This patch works?

**Comment by noblueskydropfiles** [comment]
@risturiz  If you mean current version from this repo, yes it works. Been using it since May and it did the job flawlessly with my IP changes.

**Comment by nightah** [comment]
@wimpunk are we likely to see a new release anytime soon?
Just hoping to get an ETA to understand whether it's worthwhile running the source from GitHub or alternatives instead of just waiting for a new release?

**Comment by wimpunk** [comment]
Just for your information: I'm preparing the release of v3.9.0.  Should be out soon.

**Comment by nightah** [comment]
Thanks for the heads up @wimpunk, will patiently await the release.

**Comment by wimpunk** [comment]
@nightah It's done.  You can download the package from github on https://github.com/ddclient/ddclient/releases/latest or from sourceforge on https://sourceforge.net/projects/ddclient/files/latest/download

**Comment by nightah** [comment]
Thanks @wimpunk for the prompt response and assistance.

**Comment by noblueskydropfiles** [comment]
Thank you, much appreciated.

**Pull request merged**
